### ISSUE TITLE
Deprecated: Return type of Timiki\RpcCommon\JsonRequest::jsonSerialize()

### ISSUE THREAD

**Issue by Dmutryk** [timiki/rpc-common#2]
Faced a deprecation message after updating to PHP 8.2:
Deprecated: Return type of Timiki\RpcCommon\JsonRequest::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by netesin** [comment]
thanks for you PR
